### PR TITLE
feat: update node / edge

### PR DESCRIPTION
**Pull request by sroussey**

### CODE REVIEW

**Comment by sroussey** [comment]
Still working on this. There is a lot of internal state footguns, so I will protect against those or remove some

**Comment by sroussey** [comment]
And... it doesn't work. 

`ref.current?.updateNodeData(node.id, {})` ends up removing/hiding the node which is... not what i expected.

**Comment by clarkmcc** [comment]
@sroussey yes, there are plenty of foot guns. I reported concerns with combining custom state management with the `setNodes` and `setEdges` functions on the xyflow discord and they said that they're working on cleaning this up. In the meantime, I had to introduce our own state management solution because it was preparatory to introducing node groups.

Let me know when you're happy with this and I'll take a peak

**Comment by sroussey** [comment]
OK, this is what I have been using. I took out the replace version. you can always replace everything in an update, or do a remove and add. I don't think it was usefull.

**Comment by clarkmcc** [comment]
Is this ready for review? I see there's a method commented out so wasn't sure whether you were happy with where this was at.

**Comment by sroussey** [comment]
I don't see a method commented out. It looks ready, and I've been using it.

**Pull request merged**
