### PR TITLE
Add new layouts

### PR DESCRIPTION
**Pull request by sroussey**
This adds some new layouts. Uses a graph library for DAGs that I have been working on.

image

### CODE REVIEW

**Review by clarkmcc — APPROVED** [review]
Great! These layout engines can't be used without exporting through the lib/index.ts file though.

As a side note, I'm wondering if in the future we need to expose a better API for using builtin layout engines, since you have to work with those long function names like computePipelineLayout or computeDagreLayout and then assign them to a name, and then reference that name when calling the layout function. Check out my [ChatGPT conversation](https://chat.openai.com/share/be624690-40ca-477c-85fe-a2eb0b675ae6) about a possible type-safe design.

In any case, I'm approving assuming an export of the layout functions. I just wanted to regurgitate some of my thoughts so that they can guide design decisions in the future.

**Comment by sroussey** [comment]
I refactored, so have a look.

**Comment by sroussey** [comment]
Also, I needed a graph lib, and `typescript-graph` was the first I found. It is simple, but ended up being too simple so I forked it to add the things I need and is used in this PR as `@sroussey/typescript-graph`

**Review by clarkmcc — APPROVED** [review]
lgtm!

**Pull request merged**
